### ISSUE TITLE
Add rclone example for downloading data

### ISSUE THREAD

**Issue by imrehg** [nhsx/covid-chest-imaging-database#164]
### Describe the feature request

[rclone](https://rclone.org/) might be a faster alternative to downloading stuff with the AWS CLI (especially when running things in parallel). Include that in the docs.

### Affected product area (please put an X in all the brackets that apply)

[x] Documentation
[ ] Data access
[ ] Infrastructure
[ ] Loader pipeline
[ ] Other (please describe)

### Additional context

AWS CLI is sequential, and while it's the default tool, it's not the fastest. As our database clocks in more and more data, some more effective ways would be welcome to speed stuff up.

**Comment by kaihendry** [comment]
Are you using aws cli v1 or v2 btw? I found v2 bizarrely slow. Though it nice SSO support.

**Comment by imrehg** [comment]
From the point of view of having the right commands in our docs (the main objective), I think v1 and v2 are equivalent, though haven't done much benchmarking. I think it was mostly v1 in the environments I've used, but good shout to try v2 for completeness' sake.

**Comment by imrehg** [comment]
Since no other requests were made, data users likely prefer the AWS CLI and libraries like `boto`, so closing this for now (reopen if more need arises).
